.TH "SEC\-GATHER\-PERMS" "1" "Feb 2020" "" ""
.hy
.SH NAME
.PP
sec\-gather\-perms \[en] Output files and dirs with dangerous
permissions
.SH SYNOPSIS
.PP
\f[B]sec\-gather\-perms\f[] [\f[B]\-h\f[]] [\f[B]\-\-version\f[]]
[\f[B]\-d\f[]] [\f[B]\-\-annotate\f[] \f[I]ANNOTATIONFILE\f[]] DIR [DIR
\&...]
.SH DESCRIPTION
.PP
\f[B]sec\-gather\-perms\f[] outputs files and dirs with dangerous
permissions.
Currently that means files and directories that are world\-writable or
with the setuid bit set.
.SH OPTIONS
.TP
.B \f[B]\-h\f[], \f[B]\-\-help\f[]
Display this help message and exit
.RS
.RE
.TP
.B \f[B]\-\-version\f[]
show program\[aq]s version number and exit
.RS
.RE
.TP
.B \f[B]\-d\f[] / \f[B]\-\-debug\f[]
Show debug info
.RS
.RE
.TP
.B \f[B]\-\-annotate\f[] \f[I]ANNOTATE\f[]
annotation file
.RS
.RE
.PP
positional arguments:
.TP
.B \f[B]DIR\f[]
Dir to scan
.RS
.RE
.SH EXAMPLES
.PP
Executing:
.IP
.nf
\f[C]
$\ sec\-gather\-perms\ /bin
\f[]
.fi
.PP
The default output looks like this:
.IP
.nf
\f[C]
{
\ \ \ \ "perms":\ [
\ \ \ \ \ \ \ \ {
\ \ \ \ \ \ \ \ \ \ \ \ "filename":\ "ping",
\ \ \ \ \ \ \ \ \ \ \ \ "dir":\ "/bin",
\ \ \ \ \ \ \ \ \ \ \ \ "path":\ "/bin/ping",
\ \ \ \ \ \ \ \ \ \ \ \ "type":\ "file",
\ \ \ \ \ \ \ \ \ \ \ \ "size":\ 64424,
\ \ \ \ \ \ \ \ \ \ \ \ "mode":\ 35309,
\ \ \ \ \ \ \ \ \ \ \ \ "uid":\ 0,
\ \ \ \ \ \ \ \ \ \ \ \ "gid":\ 0,
\ \ \ \ \ \ \ \ \ \ \ \ "device":\ 64769,
\ \ \ \ \ \ \ \ \ \ \ \ "trigger_modes":\ [
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ "setuid"
\ \ \ \ \ \ \ \ \ \ \ \ ],
\ \ \ \ \ \ \ \ \ \ \ \ "mode_hr":\ "\-rwsr\-xr\-x"
\ \ \ \ \ \ \ \ },
\ \ \ \ \ \ \ \ {
\ \ \ \ \ \ \ \ \ \ \ \ "filename":\ "mount",
\ \ \ \ \ \ \ \ \ \ \ \ "dir":\ "/bin",
\ \ \ \ \ \ \ \ \ \ \ \ "path":\ "/bin/mount",
\ \ \ \ \ \ \ \ \ \ \ \ "type":\ "file",
\ \ \ \ \ \ \ \ \ \ \ \ "size":\ 43088,
\ \ \ \ \ \ \ \ \ \ \ \ "mode":\ 35309,
\ \ \ \ \ \ \ \ \ \ \ \ "uid":\ 0,
\ \ \ \ \ \ \ \ \ \ \ \ "gid":\ 0,
\ \ \ \ \ \ \ \ \ \ \ \ "device":\ 64769,
\ \ \ \ \ \ \ \ \ \ \ \ "trigger_modes":\ [
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ "setuid"
\ \ \ \ \ \ \ \ \ \ \ \ ],
\ \ \ \ \ \ \ \ \ \ \ \ "mode_hr":\ "\-rwsr\-xr\-x"
\ \ \ \ \ \ \ \ },
\&...
\f[]
.fi
.PP
You can use the \f[C]reports/sec\-gather\-perms.tpl\f[] report to
generate a HTML matrix overview of dirs / files and their permissions:
.IP
.nf
\f[C]
$\ sec\-gather\-perms\ |\ sec\-report\ reports/sec\-gather\-perms.tpl\ >\ permissions.html
\f[]
.fi
.SH COPYRIGHT
.PP
Copyright 2017\-2019, Ferry Boender.
.PP
Licensed under the MIT license.
For more information, see the LICENSE file.
.SH AUTHORS
Ferry Boender.
