#!/usr/bin/env python

# Copyright 2017, Ferry Boender.
# Licensed under the MIT license. For more information, see the LICENSE file.

import sys
import argparse
import logging
import json

import tools
import common

__VERSION__ = "0.1"


def gather():
    output = tools.cmd('iptables-save')['stdout']
    return common.IptablesParser(output).parse()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Gather iptables firewall status')
    parser.add_argument('--version', action='version', version=__VERSION__)
    parser.add_argument('--debug', dest="debug", action='store_true', default=False, help="Show debug info")
    args = parser.parse_args()

    loglevel = logging.ERROR
    if args.debug is True:
        loglevel = logging.DEBUG
    logging.basicConfig(level=loglevel)

    results = gather()

    sys.stdout.write(json.dumps({"iptables": results}, indent=4))
