#!/usr/bin/env python

# Copyright 2017, Ferry Boender.
# Licensed under the MIT license. For more information, see the LICENSE file.

import sys
import argparse
import json
import logging
import pwd
import grp

__VERSION__ = "0.1"


no_login_shells = [
    '/bin/false',
    '/bin/nologin',
    '/sbin/nologin',
    '/usr/sbin/nologin'
]


def get_user_groups(username):
    groups = []

    # Get primary group
    p = pwd.getpwnam(username)
    groupname = grp.getgrgid(p.pw_gid).gr_name
    groups.append(groupname)

    # Get supplimentary groups
    for gr in grp.getgrall():
        if username in gr.gr_mem:
            groups.append(gr.gr_name)
    return groups


def gather(login=False):
    users = {}
    for p in pwd.getpwall():
        if login and p.pw_shell in no_login_shells:
            continue
        username = p.pw_name
        users[username] = {
            "homedir": p.pw_dir,
            "shell": p.pw_shell,
            "groups": get_user_groups(username)
        }

    return users


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Output unix users and their details')
    parser.add_argument('--version', action='version', version=__VERSION__)
    parser.add_argument('--debug', dest="debug", action='store_true', default=False, help="Show debug info")
    parser.add_argument('--login', dest="login", action='store_true', default=False, help="Only users that can log in")
    args = parser.parse_args()

    loglevel = logging.ERROR
    if args.debug is True:
        loglevel = logging.DEBUG
    logging.basicConfig(level=loglevel)

    unixusers = gather(login=args.login)

    sys.stdout.write(json.dumps({"unixusers": unixusers}, indent=4))
