#!/usr/bin/env python

# Copyright 2017, Ferry Boender.
# Licensed under the MIT license. For more information, see the LICENSE file.

import sys
import argparse
import os
import logging
import json

import tools
import common

__VERSION__ = "0.1"


def verify_root():
    """
    Verify the user is root.
    """
    if os.getuid() != 0:
        sys.stderr.write("iptables viewing requires you be root.\n")
        sys.exit(2)


def gather():
    output = tools.cmd('iptables-save')['stdout']
    return common.IptablesParser(output).parse()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Gather iptables firewall status')
    common.arg_add_defaults(parser, version=__VERSION__)
    args = parser.parse_args()
    common.configure_logger(args.debug)

    verify_root()

    results = gather()

    sys.stdout.write(json.dumps({"iptables": results}, indent=4))
