#!/usr/bin/env python

# Copyright 2017, Ferry Boender.
# Licensed under the MIT license. For more information, see the LICENSE file.

import sys
import argparse
import logging

__VERSION__ = "0.1"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Mail reports and alerts')
    common.arg_add_defaults(parser, version=__VERSION__, annotate=True)
    parser.add_argument('--to',
                        dest="to",
                        type=str,
                        help="Recipient email addressed (to)")
    parser.add_argument('--cc',
                        dest="cc",
                        type=str,
                        help="Recipient email addressed (cc)")
    parser.add_argument('--subject',
                        dest="subject",
                        type=str,
                        help="Subject")
    parser.add_argument('--smtp-host',
                        dest="smtp_host",
                        type=str,
                        help="SMTP host")
    args = parser.parse_args()
    common.configure_logger(args.debug)

    contents = sys.stdin.read()
    if not contents:
        # No input, don't do anything.
        sys.exit(0)

    print contents
