#!/usr/bin/env python


# Copyright 2017, Ferry Boender.
# Licensed under the MIT license. For more information, see the LICENSE file.

import sys
import argparse
import json
import logging
import tools
import re

__VERSION__ = "0.1"

last_line_re = re.compile(
    r"(?P<username>.*?)"
    r"\s+"
    r"(?P<tty>.*?)"
    r"\s+"
    r"(?P<remote_addr>.*?)"
    r"\s+"
    r"(?P<login_starttime>.*?)(   | - )"
    r"(?P<login_endtime>.*?)\s*($|\()"
    r"(?P<duration>.*?)(\)|$)"
    r".*"
)


def gather():
    last = tools.cmd("/usr/bin/last -F -w")

    results = []
    for line in last['stdout'].splitlines():
        match = last_line_re.match(line)
        if match:
            results.append(match.groupdict())
    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Output unix login sessions')
    parser.add_argument('--version', action='version', version=__VERSION__)
    parser.add_argument('--debug', dest="debug", action='store_true', default=False, help="Show debug info")

    args = parser.parse_args()
    loglevel = logging.ERROR
    if args.debug is True:
        loglevel = logging.DEBUG
    logging.basicConfig(level=loglevel)

    results = gather()

    sys.stdout.write(json.dumps({"unixsessions": results}, indent=4))
