#!/usr/bin/env python

# Copyright 2017, Ferry Boender.
# Licensed under the MIT license. For more information, see the LICENSE file.

import os
import sys
import argparse
import logging

__VERSION__ = "0.1"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Mail reports and alerts')
    parser.add_argument('--version', action='version', version=__VERSION__)
    parser.add_argument('--debug', dest="debug", action='store_true', default=False, help="Show debug info")
    parser.add_argument('--to', dest="to", type=str, help="Recipient email addressed (to)")
    parser.add_argument('--cc', dest="cc", type=str, help="Recipient email addressed (cc)")
    parser.add_argument('--subject', dest="subject", type=str, help="Subject")
    parser.add_argument('--smtp-host', dest="smtp_host", type=str, help="SMTP host")
    args = parser.parse_args()

    loglevel = logging.ERROR
    if args.debug is True:
        loglevel = logging.DEBUG
    logging.basicConfig(level=loglevel)

    contents = sys.stdin.read()
    if not contents:
        # No input, don't do anything.
        sys.exit(0)

    print contents
